server:
  port: ${SERVER_PORT:20001}
spring:
  application:
    name: natural-language-database-agent
  profiles:
    default: full-postgres
  config:
    import:
      - classpath:config/agent-common.yml

management:
  endpoints:
    web:
      exposure:
        include: health,info
