CREATE TABLE IF NOT EXISTS governed_business_rule (
    id VARCHAR(120) PRIMARY KEY,
    name VARCHAR(240) NOT NULL,
    text VARCHAR(4000) NOT NULL,
    owner VARCHAR(120) NOT NULL,
    version INTEGER NOT NULL,
    approval_status VARCHAR(40) NOT NULL,
    effective_start TIMESTAMP,
    effective_end TIMESTAMP,
    datasource_id VARCHAR(120) NOT NULL,
    tenant_id VARCHAR(120),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    content_hash VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS governed_business_rule_alias (
    rule_id VARCHAR(120) NOT NULL,
    alias VARCHAR(240) NOT NULL,
    CONSTRAINT pk_governed_business_rule_alias PRIMARY KEY (rule_id, alias),
    CONSTRAINT fk_governed_business_rule_alias_rule
        FOREIGN KEY (rule_id) REFERENCES governed_business_rule(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS governed_business_rule_schema_ref (
    rule_id VARCHAR(120) NOT NULL,
    schema_ref VARCHAR(240) NOT NULL,
    valid BOOLEAN NOT NULL DEFAULT TRUE,
    last_validated_schema_fingerprint VARCHAR(128),
    last_validated_at TIMESTAMP,
    CONSTRAINT pk_governed_business_rule_schema_ref PRIMARY KEY (rule_id, schema_ref),
    CONSTRAINT fk_governed_business_rule_schema_ref_rule
        FOREIGN KEY (rule_id) REFERENCES governed_business_rule(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS retrieval_index_rebuild_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason VARCHAR(240) NOT NULL,
    trigger_source VARCHAR(120) NOT NULL,
    affected_rule_ids VARCHAR(2000),
    affected_chunk_ids VARCHAR(4000),
    schema_fingerprint VARCHAR(128),
    embedding_model VARCHAR(120),
    outcome VARCHAR(40) NOT NULL,
    message VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_governed_business_rule_lookup
    ON governed_business_rule (datasource_id, tenant_id, active, approval_status, effective_start, effective_end);

CREATE INDEX IF NOT EXISTS idx_governed_business_rule_schema_ref_rule
    ON governed_business_rule_schema_ref (rule_id, valid);
